name: Release

permissions:
    contents: write
    id-token: write

on:
    push:
        tags:
            - "@*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  registry-url: https://registry.npmjs.org/
            - uses: pnpm/action-setup@v4
            - run: pnpm install
            - run: npx changelogithub
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - run: pnpm run build
            - run: npm install -g npm
            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
                  title: "chore(release): publish packages"
                  commit: "chore(release): update versions"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
